// <auto-generated />
namespace TravelAwayFarAway.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class spellingCheck : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(spellingCheck));
        
        string IMigrationMetadata.Id
        {
            get { return "201403222307545_spellingCheck"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
